import localFont from "next/font/local";
import "./globals.css";
import { GoogleTagManager } from "@next/third-parties/google";
import { i18n } from "@/i18n.config";
import Header from "./components/header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default async function RootLayout({ children, params }) {
  // Await the params if they're a promise
  const resolvedParams = params instanceof Promise ? await params : params;
  const lang = resolvedParams?.lang || "en"; // Fallback to 'en' if lang is undefined
  return (
    <html
      // lang="en"
      lang={lang}
    >
      <GoogleTagManager gtmId={process.env.NEXT_PUBLIC_GTM_ID} />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header lang={lang} />
        {children}
      </body>
    </html>
  );
}
