import localFont from "next/font/local";
import "./globals.css";
import AllProvider from "@/components/AllProvider";
import Nav from "@/components/nav/Nav";
import { i18n } from "@/i18n.config";

import NavBottomWrap from "@/components/navBottom/NavBottomWrap";
// import NavBottom from "@/components/navBottom/NavBottom";

// import Header from "@/components/header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default async function RootLayout({ children, params }) {
  const resolvedParams = params instanceof Promise ? await params : params;
  const lang = resolvedParams?.lang || "en"; // Fallback to 'en' if lang is undefined

  return (
    <html lang={lang}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AllProvider>
          <Nav lang={lang} />
          {children}
          <NavBottomWrap lang={lang} />
          {/* <NavBottom lang={lang} /> */}
        </AllProvider>
      </body>
    </html>
  );
}
